# ----
# Site

title: Ego Fishing Gear
url: "http://epic-goldfish.cloudvent.net"
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
snipcart_key: "NTc2ZjUxZDAtYjgwMi00MjYyLWFjOGMtMGI2YWExMTYyM2U0NjM2Mjg5MTA0MTg4MzM2OTg5"
tagline: "Designed for the Savvy Angler!"

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /images/favicon-32x32.png
description: Ego Fishing Gear
author:
  name: Ego Fishing Gear
  email: 
  twitter: 
social:
  name: Ego Fishing Gear
  links:
    - https://www.facebook.com/egofishinggear/

sale_text: 



# -----
# Build

collections:
  products:
    _hide_content: true
    output: true
  apparel:
    _hide_content: true
    output: true
  replacements:
    _hide_content: true
    output: true
  footer_products:
    _hide_content: true
    output: false

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

jekyll-archives:
  enabled:
    - categories

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

garment_types:
  - hat
  - top

social_icons:
  - Email
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS

categories:
  - ego-apparel
  - big-game-nets
  - ego-guide-nets
  - ego-tools
  - bait-nets
  - ego-trout-nets
  - kryptek-tools
  - s1-nets
  - s2-nets
  - s1-and-s2-landing-net-attachments
  - reach-nets
  - wade-kayak-nets
  - replacement-parts
  - ego-attachment-tools
  - s1-genesis-handles
  - s1-genesis-kyptek-handles
  - s2-slider-handles
  - small-hoop
  - medium-hoop
  - large-hoop
  - large22-hoop
  - xlarge-hoop
  - measure-net

replacement_types:
  bags: Mesh Bags
  hoop: Hoop
  other: Other Parts

filter_handles:
  handle_wade: Wade 6"
  handle_small: Small 13"
  handle_compact: Compact 18" - 36"
  handle_medium: Medium 25"
  handle_standard: Standard 29" - 60"
  handle_large: Large 31"
  handle_reach: Reach 48" - 108"
  handle_xlong: Extra Long 55"


filter_hoops:
  hoop_small: Small 14" x 16"
  hoop_medium: Medium 17" x 19"
  hoop_large: Large 19" x 21"
  hoop_large22: Large 22" x 23"
  hoop_xlarge: X-Large 24" x 27"

filter_meshes:
  mesh_nylon: Nylon
  mesh_ruber_coated_nylon: Ruber Coated Nylon
  mesh_pvc_coated_nylon: PVC Coated
  mesh_rubber: Rubber
  mesh_clear_rubber: Clear Rubber
  mesh_deep_rubber: Deep Rubber
  mesh_measure_net: Measure Net

tag_colors:
  new_tag: Red


_comments:
  highlight: Emphasis the text
  color: The background color used in the plan name and call to action.
  new_window: Open link in new window
  description: This is used for facebook shares of the page and google indexing
  adjustment: "Price adjustment. Examples:  +10.00 and -5.00"
  subheading: A sub heding for an item. Typically shown in smaller font below the main heading
  tag_class: "Define a color class.  Example, use tag_new for a red new tag"
  tag_text: "Example of New or On Sale"
  filter_handle: "compact, standard, reach"
  filter_hoop: "small, medium, large, large22, xlarge"
  filter_mesh:  "nylon, rugger_coated_nylon,  pvc_coated_nylon, rubber, clear_rubber, deep_rubber, measure_net"