# ----
# Site

title: Ego Fishing Gear
url: "http://epic-goldfish.cloudvent.net"
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
snipcart_key: "NTc2ZjUxZDAtYjgwMi00MjYyLWFjOGMtMGI2YWExMTYyM2U0NjM2Mjg5MTA0MTg4MzM2OTg5"
tagline: "Designed for the Savvy Angler!"

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /images/favicon-32x32.png
description: Ego Fishing Gear
author:
  name: Ego Fishing Gear
  email: 
  twitter: 
social:
  name: Ego Fishing Gear
  links:
    - https://www.facebook.com/egofishinggear/

sale_text: SPRING KICK OFF SALE  All S2 Landing Nets are 10% OFF through April 30th



# -----
# Build

collections:
  products:
    _hide_content: true
    output: true

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

jekyll-archives:
  enabled:
    - categories

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

garment_types:
  - hat
  - top

social_icons:
  - Email
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS

categories:
  - apparel
  - big-game-nets
  - ego-guide-nets
  - ego-tools
  - ego-trout-nets
  - kryptek-tools
  - s1-nets
  - s2-nets
  - s1-and-s2-landing-net-attachments
  - reach-nets
  - wade-kayak-nets
  - replacement-parts


filter_handles:
  - compact
  - standard
  - reach

filter_hoops:
  - small
  - medium
  - large
  - large22
  - xlarge

filter_meshes:
  - nylon
  - rugger_coated_nylon
  - pvc_coated_nylon
  - rubber
  - clear_rubber
  - deep_rubber
  - measure_net

tag_colors:
  tag_new: Red


_comments:
  highlight: Emphasis the text
  color: The background color used in the plan name and call to action.
  new_window: Open link in new window
  description: This is used for facebook shares of the page and google indexing
  adjustment: "Price adjustment. Examples:  +10.00 and -5.00"
  subheading: A sub heding for an item. Typically shown in smaller font below the main heading
  tag_class: "Define a color class.  Example, use tag_new for a red new tag"
  tag_text: "Example of New or On Sale"
  filter_handle: "compact, standard, reach"
  filter_hoop: "small, medium, large, large22, xlarge"
  filter_mesh:  "nylon, rugger_coated_nylon,  pvc_coated_nylon, rubber, clear_rubber, deep_rubber, measure_net"