bottom_products:
    - name: EGO Guide Nets
      link: /ego-guide-nets
      h2: EGO Guide Nets
      h3: Features a Mesasure Net
      image: /images/net_thumb1.jpg
    - name: EGO Fishing Tools
      link: /ego-guide-nets
      h2: EGO Fishing Tools
      h3: High-tech Fishing Tools for the Savvy Angler
      image: /images/net_thumb2.jpg
    - name: EGO Laure Retriver
      link: /ego-guide-nets
      h2: EGO Laure Retriver
      h3: Landing Net Accessories
      image: /images/net_thumb3.jpg
